version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.3
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
  browser-tools: circleci/browser-tools@1.4.0
  # different jobs are calles later in the workflows sections
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: 'cimg/node:16.15-browsers'
    steps:
      # install node and checkout code
      - node/install:
          node-version: '16.15'
      # install chrome driver for the frontend testing
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      # Use root level package.json to install dependencies in the frontend app
      - run:
          name: Install Front-End Dependencies
          command: |
            echo "NODE --version" 
            echo $(node --version)
            echo "NPM --version" 
            echo $(npm --version)
            npm run frontend:install
      # TODO: Install dependencies in the the backend API
      - run:
          name: Install API Dependencies
          command: |
            echo "Installing dependencies in the the backend API  "
            npm run api:install
      # TODO: Lint the frontend
      - run:
          name: Front-End Lint
          command: |
            echo "Lint the frontend"
            npm run frontend:lint
      # TODO: Build the frontend app
      - run:
          name: Front-End Build
          command: |
            echo "Build the frontend app"
            npm run frontend:build
      # TODO: Test the frontend app
      - run:
          name: Front-End Testing
          command: |
            echo "Testing the frontend app"
            npm run frontend:test
      # TODO: Build the backend API
      - run:
          name: API Build
          command: |
            echo "Build the backend API"
            npm run api:build
  # deploy step will run only after manual approval
  deploy:
    docker:
      - image: 'cimg/base:stable'
      # more setup needed for aws, node, elastic beanstalk
    steps:
      - node/install:
          node-version: '16.15'
      - eb/setup
      - aws-cli/setup
      - checkout
      - run:
          name: Deploy Frontend
          # TODO: Install, build, deploy the frontend app
          command: |
            echo "# Install, build, deploy in both apps"
            npm run frontend:install
            npm run frontend:build
            npm run frontend:deploy
      - run:
          name: Deploy Backend
          # TODO: Install, build, deploy the APIs
          command: |
            echo "# Install, build, deploy in both apps"
            npm run api:install
            npm run api:build
            npm run api:deploy

workflows:
  udagram:
    jobs:
      # Build the application
      - build
      # Wait for the manual approval to proceed with deploy
      - hold:
          filters:
            branches:
              only:
                - main
          type: approval
          requires:
            - build
      # Deploy the application after the approval
      - deploy:
          requires:
            - hold
